version: "3.7"
services:
    php:
        build:
            context: docker/php
        env_file:
            - .env
        volumes:
            - ./:/app
    mysql:
        image: mysql:8.0
        ports:
            - "33060:3306"
#        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: [ "mysqld",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--skip-character-set-client-handshake"]
        volumes:
            - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
            - mysql:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        ports:
            - "8080:8080"
        depends_on:
            - mysql
volumes:
    mysql: